# Generated by Django 5.0 on 2024-01-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cap_title', models.CharField(max_length=455)),
                ('title', models.CharField(max_length=455)),
                ('image', models.ImageField(upload_to='images')),
                ('app_store_link', models.CharField(max_length=455)),
                ('play_market_link', models.CharField(max_length=455)),
            ],
        ),
        migrations.CreateModel(
            name='HomeAppDivs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=455)),
                ('body', models.TextField()),
                ('icon', models.CharField(max_length=455)),
            ],
        ),
        migrations.CreateModel(
            name='HomeReklama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=455)),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('button_title', models.CharField(max_length=455)),
                ('button_link', models.CharField(max_length=455)),
            ],
        ),
        migrations.CreateModel(
            name='HomeResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=455)),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('button_title', models.CharField(max_length=455)),
                ('button_link', models.CharField(max_length=455)),
            ],
        ),
        migrations.CreateModel(
            name='HomeSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=455)),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='HomeSearchCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=455)),
                ('count', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HomeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=455)),
                ('icon', models.CharField(max_length=455)),
                ('body', models.TextField()),
            ],
        ),
    ]
