# Generated by Django 5.0 on 2024-01-17 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeapp',
            options={'verbose_name_plural': '6. Mobil ilova'},
        ),
        migrations.AlterModelOptions(
            name='homeappdivs',
            options={'verbose_name_plural': '7. Mobil ilova qulayliklari'},
        ),
        migrations.AlterModelOptions(
            name='homereklama',
            options={'verbose_name_plural': '4. Reklama'},
        ),
        migrations.AlterModelOptions(
            name='homeresume',
            options={'verbose_name_plural': '5. Resume'},
        ),
        migrations.AlterModelOptions(
            name='homesearch',
            options={'verbose_name_plural': '1. Qidiruv'},
        ),
        migrations.AlterModelOptions(
            name='homesearchcounter',
            options={'verbose_name_plural': '2. Qidiruv kounteri'},
        ),
        migrations.AlterModelOptions(
            name='homestep',
            options={'verbose_name_plural': '3. Qadamlar'},
        ),
    ]
