# Generated by Django 5.0 on 2023-12-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0003_alter_job_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Kutishda', 'Kutishda'), ('Aktiv', 'Aktiv')], default='Kutishda', max_length=255),
        ),
    ]
