# Generated by Django 5.0 on 2023-12-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0004_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, choices=[('Kutishda', 'Kutishda'), ('Aktiv', 'Aktiv')], default='Kutishda', max_length=255, null=True),
        ),
    ]
