# Generated by Django 5.0 on 2024-01-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0006_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons'),
        ),
    ]
