# Generated by Django 5.0 on 2024-01-12 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0007_job_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-id']},
        ),
    ]
