# Generated by Django 5.0 on 2024-01-17 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0009_job_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Ishlar'},
        ),
        migrations.AlterModelOptions(
            name='jobcategory',
            options={'verbose_name_plural': 'Ish kategoriyalari'},
        ),
        migrations.AlterModelOptions(
            name='jobregion',
            options={'verbose_name_plural': 'Viloyatlar'},
        ),
    ]
