# Generated by Django 5.0 on 2023-12-25 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OneNavbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=455)),
                ('link', models.CharField(max_length=455)),
                ('is_submenu', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SeoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=455)),
                ('author', models.CharField(max_length=455)),
                ('description', models.TextField()),
                ('favicon', models.ImageField(upload_to='favicons')),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=455)),
                ('header_logo', models.ImageField(upload_to='logos')),
                ('footer_logo', models.ImageField(upload_to='logos')),
                ('brand_name', models.CharField(max_length=455)),
            ],
        ),
        migrations.CreateModel(
            name='TwoNavbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=455)),
                ('link', models.CharField(max_length=455)),
                ('one_navbar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings_app.onenavbar')),
            ],
        ),
    ]
